---
abstract: 'Time-based checkpoints / deltas'
author:
  - 'Jane A. Avriette (jane@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-Checkpoint
no_index:
  directory:
    - t
    - inc
requires:
  Params::Validate: 0
  Test::More: 0
version: 0.36
