--- #YAML:1.0
name:               Time-Checkpoint
version:            0.35
abstract:           Time-based checkpoints / deltas
author:
    - Alex Avriette (alex@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    common::sense:     0
    Params::Validate:  0
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
